name: Deploy

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    concurrency: deploy-${{ github.head_ref || github.ref_name }}
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2

      - name: Cache vendor
        uses: actions/cache@v3
        with:
          path: |
            vendor
            !vendor/magento/magento2-base/
            ~/.composer/cache
          key: vendor-${{ hashFiles('**/composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Build artifact
        run: vendor/bin/dep artifact:build localhost

      - name: Deploy artifact
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          dep: artifact:deploy branch=${{ github.head_ref || github.ref_name }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Artifact - ${{ github.head_ref || github.ref_name }}
          path: |
            artifacts/artifact.tar.gz
